name: uni_ride
description: "Transporte entre estudiantes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # GestiÃ³n de estado
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.0
  firebase_storage: ^12.4.10

  # --- MAPAS Y RUTAS (NUEVO) ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  geolocator: ^11.0.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/